### ISSUE TITLE
about code

### ISSUE THREAD

**Issue by lyy520ljh** [Lusani/SDN-Controller-Placement#1]
#Finds optimal locations to place controllers using a ping procedure.
How to find it by using a ping procedure?
What results may I see?

**Comment by Lusani** [comment]
Hi,
Please refer to attachments below. 

![image](https://user-images.githubusercontent.com/29731494/55627402-6318b380-57ae-11e9-97ed-a3578f5b2e88.png)
The following figure summarizes the procedure.
![image](https://user-images.githubusercontent.com/29731494/55627131-b9392700-57ad-11e9-8a37-a42b4301e422.png)

Let me know if this helps.
